// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Elders.Cronus.DomainModelling")]
[assembly: AssemblyDescriptionAttribute("Elders.Cronus.DomainModelling")]
[assembly: AssemblyProductAttribute("Elders.Cronus.DomainModelling")]
[assembly: AssemblyVersionAttribute("1.1.37")]
[assembly: AssemblyInformationalVersionAttribute("1.1.37")]
[assembly: AssemblyFileVersionAttribute("1.1.37")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.1.37";
    }
}
