// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Elders.Cronus")]
[assembly: AssemblyDescriptionAttribute("Elders.Cronus")]
[assembly: AssemblyProductAttribute("Elders.Cronus")]
[assembly: AssemblyVersionAttribute("1.2.2")]
[assembly: AssemblyInformationalVersionAttribute("1.2.2")]
[assembly: AssemblyFileVersionAttribute("1.2.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.2.2";
    }
}
