// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Elders.Cronus")]
[assembly: AssemblyDescriptionAttribute("Elders.Cronus")]
[assembly: GuidAttribute("b422fc04-22de-40ec-978f-bf89fc017411")]
[assembly: AssemblyProductAttribute("Elders.Cronus")]
[assembly: AssemblyVersionAttribute("1.1.37")]
[assembly: AssemblyInformationalVersionAttribute("1.1.37")]
[assembly: AssemblyFileVersionAttribute("1.1.37")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.1.37";
    }
}
