---
variables:
  - group: elders-nuget
  - name: PROJECT_DIR
    value: Elders.Cronus

trigger:
  branches:
    include: [master,beta,preview,"*.x"]
  paths:
    exclude: [CHANGELOG.md]

pr: none

pool:
  vmImage: 'ubuntu-22.04'

stages:
- stage: RunTestsDotnet10
  displayName: 'Run tests for dotnet 10'
  jobs:
  - job: run_tests

    steps:
    - checkout: self
      clean: true
      persistCredentials: true

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '10.x'
        includePreviewVersions: false

    - task: DotNetCoreCLI@2
      name: test
      inputs:
        command: test
        projects: '**/*Tests.csproj'
        arguments: '--framework net10.0'

- stage : DeployStage
  displayName: 'Deploy stage'
  dependsOn:
    - RunTestsDotnet10

  jobs:
  - job: build_pack_publish

    steps:
    - checkout: self
      clean: true
      persistCredentials: true

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '10.x'
        includePreviewVersions: false

    - task: DotNetCoreCLI@2
      name: build
      inputs:
        command: build
        projects: 'src/$(PROJECT_DIR)/*.csproj'

    - task: Bash@3
      name: release
      displayName: semantic release + pack
      env:
        STAGING_PATH: $(Build.StagingDirectory)
      inputs:
        targetType: 'inline'
        script: |
          time curl -L https://github.com/Elders/blob/releases/download/SemRel-01/node_modules.tar.gz | tar mx -I pigz
          time npx semantic-release --no-ci
          # few commands for debugging purposes
          ls -l $STAGING_PATH/*.nupkg
          echo dotnet msbuild `dotnet msbuild --version`
          echo dotnet nuget `dotnet nuget --version`
          echo dotnet `dotnet --version`

    - task: Bash@3
      name: publish
      displayName: nuget push to nuget.org
      condition: and(eq(variables['newVer'], 'yes'), succeeded())
      inputs:
        targetType: 'inline'
        script: 'dotnet nuget push $(Build.StagingDirectory)/*.nupkg --api-key $(NUGET_KEY) --source https://api.nuget.org/v3/index.json --skip-duplicate'
